### ISSUE TITLE
other_agents

### ISSUE THREAD

**Issue by Xiyou521** [bupi-lu/MY_MADDPG#1]
请问你看明白other_agents的作用了吗？我最近也在看这个代码，环境想要换成simple_spread，但是收敛的奖励一直是负的，注释other_agents的结果更差，期待您的解答。

**Comment by bupi-lu** [comment]
我不太清楚他的这个作用 我感觉没啥用 我写自己的环境时 把这个去掉了 只训练对应自己需要的agent 应该就没啥问题

**Comment by Xiyou521** [comment]
好的，非常感谢您的回答。
